//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AgarRunner.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


import javax.swing.*;

public class AgarRunner
{
    public JFrame frame;

    public static void main( String[] args )
    {

    }
}
