//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AvoidLarger.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


public class AvoidLarger extends StepStrategy
{
    public AvoidLarger( Object o )
    {

    }
}
