//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BasicCell.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


import java.awt.*;

public class BasicCell extends Cell
{
    public BasicCell( String name )
    {
        this.cellsSwallowed = 0;
        //TODO: choose an appropriate speed value
        this.speed = 100;
        this.color = new Color( (int) ( Math.random() % 256 ), (int) ( Math.random() % 256 ), (int) ( Math.random() % 256 ) );
        //TODO: choose an appropriate mass value
        this.mass = 60;
        this.foodEaten = 0;
        this.name = name;
    }

    @Override
    public void draw( Graphics2D g2d )
    {

    }
}
