//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CellDecorator.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


import java.awt.*;

public abstract class CellDecorator extends Cell
{
    public CellDecorator( Cell cell )
    {

    }

    public void draw( Graphics2D g2d )
    {

    }
}
