//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cell.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


import java.awt.*;

public abstract class Cell extends Entity
{
    public String name;
    public int foodEaten;
    public int cellsSwallowed;

    public void addMass( double additionalMass )
    {

    }

    public void removeMass( double reductionalMass )
    {

    }

    public void draw( Graphics2D g2d )
    {

    }
}
