//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ChaseSmaller.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


public class ChaseSmaller extends StepStrategy
{
    public ChaseSmaller( Object o )
    {

    }
}
