//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Entity.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


import java.awt.*;

public abstract class Entity
{
    public Color color;
    public double mass;
    public double speed;
    public StepStrategy strategy;

    public void step( double deltaTime )
    {

    }

    public abstract void draw( Graphics2D g2d );
}
