//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Environment.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


import java.awt.image.BufferedImage;
import java.util.ArrayList;

public class Environment
{
    public int windowWidth;
    public int windowHeight;
    public BufferedImage logo;
    public int numberOfSteps;
    public ArrayList<Entity> entities;
    public RandomFactory randomFactory;

    public Environment( int windowWidth, int windowHeight, int leftPanelWidth, BufferedImage logo )
    {
        this.windowWidth = windowWidth;
        this.windowHeight = windowHeight;
        this.logo = logo;

        this.entities = new ArrayList<>();

        this.randomFactory = new RandomFactory( windowWidth, windowHeight );
    }


    public StepStrategy generateSugarStepStrategy()
    {
        return null;
    }

    public StepStrategy generateOrganismStepStrategy()
    {
        return null;
    }

    public StepStrategy generateCellStepStrategy( Cell cell )
    {
        return null;
    }

    public Food createFood( FoodFactory factory )
    {
        return factory.createFood( this );
    }

    public Cell createCell()
    {
        BasicCell basicCellToBeCreated = new BasicCell( randomFactory.generateName() );

        entities.add( basicCellToBeCreated );
        return basicCellToBeCreated;
    }

    public void stepAll( double deltaTime )
    {

    }

    public int getWindowWidth()
    {
        return windowWidth;
    }

    public void setWindowWidth( int windowWidth )
    {
        this.windowWidth = windowWidth;
    }

    public int getWindowHeight()
    {
        return windowHeight;
    }

    public void setWindowHeight( int windowHeight )
    {
        this.windowHeight = windowHeight;
    }

    public BufferedImage getLogo()
    {
        return logo;
    }

    public void setLogo( BufferedImage logo )
    {
        this.logo = logo;
    }

    public int getNumberOfSteps()
    {
        return numberOfSteps;
    }

    public void setNumberOfSteps( int numberOfSteps )
    {
        this.numberOfSteps = numberOfSteps;
    }

    public ArrayList<Entity> getEntities()
    {
        return entities;
    }

    public void setEntities( ArrayList<Entity> entities )
    {
        this.entities = entities;
    }

    public static void main( String[] args )
    {
        Environment testEnv = new Environment( 1024, 768, 30, new BufferedImage( 1, 1, 1 ) );

        ArrayList<Entity> entityArrayList = new ArrayList<>();
        SugarFactory sugarFactory = new SugarFactory();

        for ( int i = 0; i < 56; i++ )
        {
            testEnv.createFood( sugarFactory );
        }
    }
}

