//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Food.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


import java.awt.*;

public abstract class Food extends Entity
{
    public abstract void draw( Graphics2D g2d );
}
