//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FoodFactory.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


public abstract class FoodFactory
{
    public abstract Food createFood( Environment env );
}
