//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GameDisplayPanel.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


import javax.swing.*;
import java.awt.*;

public class GameDisplayPanel extends JPanel
{
    public GameDisplayPanel( Environment environment )
    {

    }

    public Dimension getPreferredSize()
    {
        return null;
    }

    public void paintComponent( Graphics g )
    {

    }
}
