//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GrabFood.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


public class GrabFood extends StepStrategy
{
    public GrabFood( Object o )
    {

    }
}
