//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LoseMass.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


public class LoseMass extends StepStrategy
{
    public double losePercantage;

    public LoseMass( Object o )
    {

    }
}
