//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MoveRandom.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


public class MoveRandom extends StepStrategy
{
    public MoveRandom( Object o )
    {

    }
}
