//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MoveLinear.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


public class MoveLinear extends StepStrategy
{
    public MoveLinear( Object o )
    {

    }
}
