//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OrganismFactory.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


public class OrganismFactory extends FoodFactory
{
    @Override
    public Food createFood( Environment env )
    {
        Organism organismToBeCreated = new Organism();

        organismToBeCreated.mass = Math.random();
        organismToBeCreated.color = RandomFactory.generateColor();
        // TODO: make organism speed a small value
        organismToBeCreated.speed = 15;
        organismToBeCreated.step( (double) 0 );
        // TODO: decide a appropriate radius value
        organismToBeCreated.radius = 40;

        env.entities.add( organismToBeCreated );
        return organismToBeCreated;
    }
}