//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Organism.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


import java.awt.*;

public class Organism extends Food
{
    public double radius;

    public void draw( Graphics2D g2d )
    {

    }
}
