//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Roamer.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


import java.awt.*;

public class Roamer extends CellDecorator
{
    public Roamer( Cell cell )
    {
        super( cell );
    }

    public void draw( Graphics2D g2d )
    {

    }
}
