//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StandStill.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


public class StandStill extends StepStrategy
{
    public StandStill( Object o )
    {

    }
}
