//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sugar.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


import java.awt.*;

public class Sugar extends Food
{
    public int sideHalfLength;

    public void draw( Graphics2D g2d )
    {

    }
}
