//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vector.java
//  @ Date : 18.11.2015
//  @ Author : 
//
//


public class Vector
{
    public double x;
    public double y;

    public Vector( double x, double y )
    {
        this.x = x;
        this.y = y;
    }

    public void normalize()
    {
        double length = Math.sqrt( Math.pow( this.x, 2 ) + Math.pow( this.y, 2 ) );
        this.x = x / length;
        this.y = y / length;
    }

    public double distanceTo( Vector other )
    {
        return Math.sqrt( Math.pow( other.x - this.x, 2 ) + Math.pow( other.y - this.y, 2 ) );
    }
}